import { Header } from "@/components/header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, FileText, TrendingUp, Calendar, Eye, Home } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export default function Reports() {
  const [, setLocation] = useLocation();
  const [selectedReport, setSelectedReport] = useState<any>(null);
  const [previewOpen, setPreviewOpen] = useState(false);
  const reports = [
    {
      id: 1,
      name: "Monthly Cost Analysis - January 2025",
      type: "Cost Analysis",
      date: "2025-01-12",
      size: "2.4 MB"
    },
    {
      id: 2,
      name: "Project Status Report - Q4 2024",
      type: "Status Report",
      date: "2024-12-31",
      size: "1.8 MB"
    },
    {
      id: 3,
      name: "BIM Takeoff Summary - Kmart Gladstone",
      type: "BIM Report",
      date: "2025-01-10",
      size: "5.2 MB"
    },
    {
      id: 4,
      name: "Material Cost Comparison",
      type: "Cost Analysis",
      date: "2025-01-05",
      size: "892 KB"
    }
  ];

  const handleDownload = (report: any) => {
    // Create a mock PDF content
    const content = `ESTIMATE REPORT
    
Report: ${report.name}
Type: ${report.type}
Date: ${new Date(report.date).toLocaleDateString('en-AU')}
File Size: ${report.size}

PROJECT SUMMARY
================
This is a professional construction cost estimation report generated by EstiMate.

COST BREAKDOWN
--------------
Materials: $450,000
Labor: $320,000
Equipment: $180,000
Overheads: $125,000
Contingency: $85,000

TOTAL PROJECT COST: $1,160,000

Notes: This is a preview/demo report. Full reports include detailed breakdowns,
material schedules, labor allocations, and project timelines.`;

    // Create a blob and download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <Header />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Reports</h1>
            <p className="text-gray-600 mt-1">Access your construction reports and analytics</p>
          </div>
          <div className="flex gap-2">
            <Button 
              variant="outline"
              onClick={() => setLocation("/")}
            >
              <Home className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <Button className="bg-gradient-to-r from-orange-500 to-orange-600 hover:from-orange-600 hover:to-orange-700">
              <FileText className="w-4 h-4 mr-2" />
              Generate Report
            </Button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Reports</CardTitle>
              <FileText className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">47</div>
              <p className="text-xs text-muted-foreground">+12 this month</p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Cost Savings</CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$234,500</div>
              <p className="text-xs text-muted-foreground">Identified through analysis</p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Last Generated</CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">Today</div>
              <p className="text-xs text-muted-foreground">2 hours ago</p>
            </CardContent>
          </Card>
        </div>

        {/* Reports List */}
        <Card>
          <CardHeader>
            <CardTitle>Recent Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {reports.map(report => (
                <div key={report.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50 transition-colors">
                  <div className="flex items-center gap-4">
                    <FileText className="w-10 h-10 text-orange-600" />
                    <div>
                      <h3 className="font-semibold">{report.name}</h3>
                      <p className="text-sm text-gray-600">
                        {report.type} • {new Date(report.date).toLocaleDateString('en-AU')} • {report.size}
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => {
                        setSelectedReport(report);
                        setPreviewOpen(true);
                      }}
                    >
                      <Eye className="w-4 h-4 mr-2" />
                      Preview
                    </Button>
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => handleDownload(report)}
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Preview Dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{selectedReport?.name}</DialogTitle>
            <DialogDescription>
              {selectedReport?.type} • Generated on {selectedReport && new Date(selectedReport.date).toLocaleDateString('en-AU')}
            </DialogDescription>
          </DialogHeader>
          
          <div className="mt-4 space-y-4">
            <div className="border rounded-lg p-6 bg-gray-50">
              <h3 className="text-lg font-semibold mb-4">Executive Summary</h3>
              <p className="text-gray-700">
                This construction cost estimation report provides a comprehensive analysis of the project requirements,
                material costs, labor allocations, and timeline projections for optimal project execution.
              </p>
            </div>

            <div className="border rounded-lg p-6">
              <h3 className="text-lg font-semibold mb-4">Cost Breakdown</h3>
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left py-2">Category</th>
                    <th className="text-right py-2">Amount (AUD)</th>
                    <th className="text-right py-2">Percentage</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b">
                    <td className="py-2">Materials</td>
                    <td className="text-right">$450,000</td>
                    <td className="text-right">38.8%</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-2">Labor</td>
                    <td className="text-right">$320,000</td>
                    <td className="text-right">27.6%</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-2">Equipment</td>
                    <td className="text-right">$180,000</td>
                    <td className="text-right">15.5%</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-2">Overheads</td>
                    <td className="text-right">$125,000</td>
                    <td className="text-right">10.8%</td>
                  </tr>
                  <tr className="border-b">
                    <td className="py-2">Contingency</td>
                    <td className="text-right">$85,000</td>
                    <td className="text-right">7.3%</td>
                  </tr>
                  <tr className="font-bold">
                    <td className="py-2">Total</td>
                    <td className="text-right">$1,160,000</td>
                    <td className="text-right">100%</td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div className="border rounded-lg p-6 bg-orange-50">
              <h3 className="text-lg font-semibold mb-2">Key Insights</h3>
              <ul className="list-disc list-inside space-y-1 text-gray-700">
                <li>Material costs align with current Australian market rates</li>
                <li>Labor allocation includes all trade specializations</li>
                <li>Contingency buffer provides adequate risk mitigation</li>
                <li>Timeline projections account for seasonal variations</li>
              </ul>
            </div>

            <div className="flex justify-end gap-2 pt-4">
              <Button variant="outline" onClick={() => setPreviewOpen(false)}>
                Close
              </Button>
              <Button 
                className="bg-gradient-to-r from-orange-500 to-orange-600"
                onClick={() => {
                  handleDownload(selectedReport);
                  setPreviewOpen(false);
                }}
              >
                <Download className="w-4 h-4 mr-2" />
                Download Full Report
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}